create table public.fms_rp_entry_gsolution_thienlong_2601 (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  created_by text null,
  phone_number text null,
  customer_name text null,
  bill_number text null,
  sale_data jsonb null,
  gift_data jsonb null,
  other_data jsonb null,
  location_code text null,
  location_name text null,
  workshift_id text null,
  workshift_name text null,
  constraint fms_rp_entry_gsolution_thienlong_2601_pkey primary key (id)
) TABLESPACE pg_default;

-- Add trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fms_rp_entry_gsolution_thienlong_2601_updated_at 
  BEFORE UPDATE ON public.fms_rp_entry_gsolution_thienlong_2601 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();
